version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    hostname: vtaxerdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: vtaxerdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vtaxerdbpass

  vtaxer-core:
    image: vtaxer-core  # Replace with your actual image name
    container_name: vtaxer-core
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:vtaxerdbpass@mongo:27017/vtaxerdb
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
