# spring.data.mongodb.database=vtaxerdb
# spring.data.mongodb.uri=mongodb://localhost:27017/vtaxerdb  
-spring.data.mongodb.uri=mongodb://localhost:27017/vtaxerMain
server.port=8080

# Enable and configure file upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.error.include-message=always
server.error.include-binding-errors=always

spring.security.oauth2.client.registration.google.client-id=1084731179966-q28p4500qkc8bc9glom1ra74tk5q6soe.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET_HERE
spring.security.oauth2.client.registration.google.scope=email,profile

google.clientId=1084731179966-q28p4500qkc8bc9glom1ra74tk5q6soe.apps.googleusercontent.com

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google